### PR TITLE
Experimental support for Zigbuild

### PR DESCRIPTION
**Pull request by hammerhg**
This adds support for Zig builds for easy and fast cross-compilation

### CODE REVIEW

**Comment by missingdays** [comment]
Hey @hammerhg 
Thanks for the pull request! Sorry for a long reply, I was on vacation last 2 weeks

I see in `README` you mention that the user needs to install `cargo-zigbuild` on the agent manually. TeamCity can instead install it automatically before running the build step, as we do with `clippy` for example. Do you think this approach would work? Or would it potentially break something?

**Comment by hammerhg** [comment]
@missingdays thanks for your reply.

It should work, I'll test and update the PR.

**Comment by missingdays** [comment]
@hammerhg I received a request to also support `cargo-deny` and `cargo-about` in the plugin, which got me thinking if we could actually support running any custom crate instead of hardcoding each one of them

So the configuration would be quite simple - you specify a crate, in your case `zigbuild`, and any additional arguments. 
TeamCity then would install `cargo-zigbuild` and run it with provided additional arguments

I think this approach should also work for your case as well, without the need for new `ArgumentsProvider` and `CommandType`

**Comment by hammerhg** [comment]
@missingdays I fully agree that custom crate support is way more flexible then adding support one-by-one and thanks for looking at bigger picture. I suggest to close this PR and work on the custom create support.

Is anyone already working on this?

If not, I could potentially work on this, but it will take 2-3 weeks with my current availability.

**Comment by missingdays** [comment]
@hammerhg #60 is already fixed, see this commit https://github.com/JetBrains/teamcity-rust-plugin/commit/853e1a106016fa0ea8ab8a6db1ec196ee0a2a477

**Pull request closed without merging**
